### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./waflib`

### CODE REVIEW

**Comment by drobilla** [comment]
Phew, quite a few!  Looks good to me, thanks.  Maybe a good tool to add to my maintenance toolbox...

Before I merge though, it seems that your git client may not be configured, judging by the default github email address:

    luz paz <luzpaz@users.noreply.github.com>
    
How do you wish to be attributed?  We generally prefer

    Real Name <usual@working.email.address.com>
    
Though you can use whatever you want (just checking because this happens by mistake sometimes when people move to a new machine or git client)

**Comment by luzpaz** [comment]
I don't mind. Please use what default is ATM.

**Comment by luzpaz** [comment]
@drobilla any possibility to merge this soon?

**Comment by luzpaz** [comment]
@drobilla any plan on merge soon?

**Comment by drobilla** [comment]
Fixed in bd70bc9

**Comment by drobilla** [comment]
Oops.  aaaaaaaaaaaaaaaand 2ab9078

**Pull request closed without merging**
