### PR TITLE
Add UI scale & color extensions

### PR DESCRIPTION
**Pull request by x42**

### CODE REVIEW

**Comment by x42** [comment]
Some typos to be fixed.. documentation also need to be clarified (scale relative to what) and
RGBA data-type could be an atom:chunk or array of bytes..   TBD

**Comment by drobilla** [comment]
Part of me wants to argue that color is so fundamental it might even be worth a proper atom type.  Ignoring the smell of the signed/unsigned cast thing, this gets the job done, but maybe plugins being able to communicate colors to each other, or their UIs, or the host, and have that al be transparent and serialized nicely isn't so crazy...

**Comment by x42** [comment]
RGBA32 is an established standard, there may already be some RDF vocab for it.

**Comment by drobilla** [comment]
In the interest of actually getting things done, I punted on the type problem and just documented the current practice in the comment instead.

Merged as ef7231b465b5b3bf24b6d4d437af460ef5910099, thanks.

**Pull request closed without merging**
